name: Keepalive

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  tests:
    name: Run integration tests
    steps:
      - uses: actions/checkout@v4
      # … whatever other steps you need to run your tests

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
